name: build-and-test
run-name: "Build and Test"
on: [push]

permissions:
  contents: write # Required to create a release
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
  security-events: write

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: dotnet format check
      run: dotnet format --exclude-diagnostics CliFx_SystemConsoleShouldBeAvoided
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /p:WarningLevel=0
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: >
        cd SteamPrefill.Test;
        dotnet test --no-restore -c Release /p:WarningLevel=0
  infersharp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Debug
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v1.3.1
      id: runinfersharp
      with:
        binary-path: SteamPrefill/bin/Debug/net6.0
        optional-flags: --enable-null-dereference --enable-dotnet-resource-leak --enable-thread-safety-violation
    - name: Upload SARIF output to GitHub Security Center
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: infer-out/report.sarif
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ['win-x64', 'linux-x64', 'linux-arm64', 'osx-x64']
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    # Gets the executable version that will be used later in the uploaded zip file name
    - name: Set Version
      id: vars
      run: >
        version=$(grep -Po '(?<=<Version>)(.*?)(?=</Version>)' SteamPrefill/SteamPrefill.csproj);
        echo "version=$version" >> $GITHUB_OUTPUT;
    - run: sudo apt-get update
    - run: sudo apt-get install zip -y
    - name: Publish
      # WarningLevel=0 so that the Annotations don't hide the Artifact list
      run: >
        dotnet publish SteamPrefill/SteamPrefill.csproj \
          --nologo \
          -o "publish/SteamPrefill-${{ steps.vars.outputs.version }}-${{ matrix.runtime }}" \
          -c Release \
          --runtime "${{ matrix.runtime }}" \
          --self-contained true \
          /p:WarningLevel=0 \
          /p:PublishSingleFile=true \
          /p:PublishReadyToRun=true \
          /p:PublishTrimmed=true
        cd publish;
        zip -r SteamPrefill-${{ steps.vars.outputs.version }}-${{ matrix.runtime }}.zip SteamPrefill-${{ steps.vars.outputs.version }}-${{ matrix.runtime }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: SteamPrefill-${{ steps.vars.outputs.version }}-${{ matrix.runtime }} 
        path: publish
        if-no-files-found: error
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        name: "v${{ steps.vars.outputs.version }}"
        files: "**/*.zip" 
        generate_release_notes: true