name: release-publish
run-name: "Publish Release"

on:
  push:
    tags:
      - '*'

permissions:
  contents: write # Required to create a release

jobs:
  dotnet-publish:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    strategy:
      matrix:
        runtime: ['win-x64', 'linux-x64', 'linux-arm64', 'osx-x64']
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # Gets the executable version that will be used later in the uploaded zip file name
    - name: Set Version
      id: vars
      run: |
        version=$(grep -Po '(?<=<VersionPrefix>)(.*?)(?=</VersionPrefix>)' SteamPrefill/SteamPrefill.csproj); 
        echo "version=$version" >> $GITHUB_OUTPUT;
    - run: apt-get update
    - run: apt-get install zip -y
    - name: Publish 
      run: >
        version=${{ steps.vars.outputs.version }}

        dotnet publish SteamPrefill/SteamPrefill.csproj \
          --nologo \
          -o "publish/SteamPrefill-$version-${{ matrix.runtime }}" \
          -c Release \
          --runtime "${{ matrix.runtime }}" \
          --self-contained true \
          /p:PublishSingleFile=true \
          /p:PublishReadyToRun=true \
          /p:PublishTrimmed=true;

        cd publish;

        zip -r SteamPrefill-$version-${{ matrix.runtime }}.zip SteamPrefill-$version-${{ matrix.runtime }};
        cp SteamPrefill-$version-${{ matrix.runtime }}.zip ../;
        rm SteamPrefill-$version-${{ matrix.runtime }}.zip;
        cd ..;
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: SteamPrefill-${{ steps.vars.outputs.version }}-${{ matrix.runtime }} 
        path: publish/
        if-no-files-found: error
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        name: "v${{ steps.vars.outputs.version }}"
        files: "**/*.zip" 
        generate_release_notes: true
  docker-publish-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: >
        dotnet publish SteamPrefill/SteamPrefill.csproj \
          --nologo \
          -o publish \
          -c Release \
          --runtime "linux-x64" \
          --self-contained true \
          /p:PublishSingleFile=true \
          /p:PublishReadyToRun=true \
          /p:PublishTrimmed=true
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: tpill90/steam-lancache-prefill
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}